# Generated by Django 5.1.6 on 2025-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('save_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('secondary_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section', models.CharField(choices=[('superDeals', 'Super Deals'), ('bigSave', 'Big Save')], max_length=20)),
            ],
        ),
    ]
