# Generated by Django 5.1.6 on 2025-04-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_advertising'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='image_url',
        ),
        migrations.AddField(
            model_name='advertising',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
