# Generated by Django 5.1.6 on 2025-04-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_advertising_image_url_advertising_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
