# Generated by Django 5.1.6 on 2025-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_deliveryorder_shippingprice_deliveryorder_taxprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='trackingNumber',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
    ]
