# Generated by Django 5.1.6 on 2025-05-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveredBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
