# Generated by Django 5.1.6 on 2025-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_deliveredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveredBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
